# Generated by Django 5.0.3 on 2024-03-11 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="helper",
            name="skills",
        ),
        migrations.AddField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="helper",
            name="user",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="helper",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill",
                to="main.helper",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="rating",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="helper",
            name="age",
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name="helper",
            name="phone",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
